//> using scala "2.12.18"
//> using dep "com.github.spinalhdl::spinalhdl-core:1.13.0"
//> using dep "com.github.spinalhdl::spinalhdl-lib:1.13.0"
//> using plugin "com.github.spinalhdl::spinalhdl-idsl-plugin:1.13.0"
//> using test.dep "org.scalatest::scalatest:3.2.18"
//> using test.dep "com.github.spinalhdl::spinalhdl-tester:1.13.0"
//> using dep "org.scodec::scodec-core:1.11.10"
//> using dep "org.scodec::scodec-bits:1.1.38"
//> using options "-deprecation" "-feature" "-unchecked"
